package com.jibo.dao;

import android.database.sqlite.SQLiteDatabase;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.IdentityScopeType;

import com.jibo.dao.FormulaCategoryDao;
import com.jibo.dao.FormulaDao;
import com.jibo.dao.CategoryFormulaMappingDao;
import com.jibo.dao.FormulaRankDao;
import com.jibo.dao.UnitsDao;
import com.jibo.dao.UnitValuesDao;
import com.jibo.dao.CalcSearchDao;
import com.jibo.dao.DptRelationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoManager extends AbstractDaoMaster {

	/** Creates underlying database table using DAOs. */
	public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
	}

	/** Drops underlying database table using DAOs. */
	public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
	}

	public DaoManager(DBHelper helper) {
		super(helper.getSQLiteDatabase(), helper.getDbversion());
		this.helper = helper;
		if (helper.isSDCardDB()) {
			registerDaoClass(FormulaCategoryDao.class);
			registerDaoClass(FormulaDao.class);
			registerDaoClass(CategoryFormulaMappingDao.class);
			registerDaoClass(FormulaRankDao.class);
			registerDaoClass(UnitsDao.class);
			registerDaoClass(UnitValuesDao.class);
			registerDaoClass(CalcSearchDao.class);
			registerDaoClass(DptRelationDao.class);

			registerDaoClass(DrugInfoDao.class);
			registerDaoClass(BrandInfoDao.class);
			registerDaoClass(CompanyInfoDao.class);
			registerDaoClass(TADrugDao.class);
			registerDaoClass(TADrugRefDao.class);
			registerDaoClass(DrugDetailInfoDao.class);
			registerDaoClass(DrugDetailTypeInfoDao.class);
			registerDaoClass(AdminRouteInfoDao.class);
			registerDaoClass(FormulationInfoDao.class);
			registerDaoClass(AhfsDrugInfoDao.class);
			
			registerDaoClass(ContactManufutureDao.class);
		    registerDaoClass(ManufutureBrandInfoDao.class);
		    
		    registerDaoClass(HospitalProvinceDao.class);
	        registerDaoClass(HospitalCityDao.class);
	        registerDaoClass(HospitalDao.class);
	        registerDaoClass(DepartmentDao.class);
	        registerDaoClass(SearchDrugDao.class);
	        registerDaoClass(VersionDao.class);
		} else {

		}
	}

	private DBHelper helper;

	public DaoSession newSession() {
		return new DaoSession(helper, IdentityScopeType.Session, daoConfigMap);
	}

	public DaoSession newSession(IdentityScopeType type) {
		return new DaoSession(helper, type, daoConfigMap);
	}

}
