package com.jibo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table calc_searchtag.
 * 
 * 医学公式模块 - 公式搜索表
 * 
 */
public class CalcSearch {

    private Integer id;
    private String calMobile;
    private String keyWord;

    public CalcSearch() {
    }

    public CalcSearch(Integer id) {
        this.id = id;
    }

    public CalcSearch(Integer id, String calMobile, String keyWord) {
        this.id = id;
        this.calMobile = calMobile;
        this.keyWord = keyWord;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCalMobile() {
        return calMobile;
    }

    public void setCalMobile(String calMobile) {
        this.calMobile = calMobile;
    }

    public String getKeyWord() {
        return keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

}
