package com.jibo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CompanyInfo.
 * 
 * 药品对应公司表
 * 
 */
public class CompanyInfo implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 299240314099328693L;
	private String id;
    private String nameCn;
    private String nameEn;
    private String changeDate;

    public CompanyInfo() {
    }

    public CompanyInfo(String id) {
        this.id = id;
    }

    public CompanyInfo(String id, String nameCn, String nameEn, String changeDate) {
        this.id = id;
        this.nameCn = nameCn;
        this.nameEn = nameEn;
        this.changeDate = changeDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNameCn() {
        return nameCn;
    }

    public void setNameCn(String nameCn) {
        this.nameCn = nameCn;
    }

    public String getNameEn() {
        return nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getChangeDate() {
        return changeDate;
    }

    public void setChangeDate(String changeDate) {
        this.changeDate = changeDate;
    }

}
