package com.jibo.entity;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table dpt_replation.
 * 
 * 科室对应各模块的类别信息关联表
 * 
 */
public class DptRelation {

    private String department;
    private Integer calculatorId;//------------科室对应公式数据的类别id
    private String calculatorCategory;//-------科室对应公式数据的类别
    private String drugCategory ;//------------科室对应药品数据的类别
    private String drugCategoryId;//-----------科室对应药品数据的类别id
    private String articleCategory;//----------科室对应医学研究的类别
    private String articleCategoryId;//--------科室对应医院研究的类别id

    public DptRelation() {
    }

    public DptRelation(String department) {
        this.department = department;
    }

    public DptRelation(String department, Integer calculatorId, String calculatorCategory) {
        this.department = department;
        this.calculatorId = calculatorId;
        this.calculatorCategory = calculatorCategory;
    }
    
    

    public DptRelation(String department, Integer calculatorId,
			String calculatorCategory, String drugCategory,
			String drugCategoryId) {
		super();
		this.department = department;
		this.calculatorId = calculatorId;
		this.calculatorCategory = calculatorCategory;
		this.drugCategory = drugCategory;
		this.drugCategoryId = drugCategoryId;
	}

    public DptRelation(String department, Integer calculatorId,
			String calculatorCategory, String drugCategory,
			String drugCategoryId, String articleCategory,
			String articleCategoryId) {
		super();
		this.department = department;
		this.calculatorId = calculatorId;
		this.calculatorCategory = calculatorCategory;
		this.drugCategory = drugCategory;
		this.drugCategoryId = drugCategoryId;
		this.articleCategory = articleCategory;
		this.articleCategoryId = articleCategoryId;
	}

	public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public Integer getCalculatorId() {
        return calculatorId;
    }

    public void setCalculatorId(Integer calculatorId) {
        this.calculatorId = calculatorId;
    }

    public String getCalculatorCategory() {
        return calculatorCategory;
    }

    public void setCalculatorCategory(String calculatorCategory) {
        this.calculatorCategory = calculatorCategory;
    }

	public String getDrugCategory() {
		return drugCategory;
	}

	public void setDrugCategory(String drugCategory) {
		this.drugCategory = drugCategory;
	}

	public String getDrugCategoryId() {
		return drugCategoryId;
	}

	public void setDrugCategoryId(String drugCategoryId) {
		this.drugCategoryId = drugCategoryId;
	}

	public String getArticleCategory() {
		return articleCategory;
	}

	public void setArticleCategory(String articleCategory) {
		this.articleCategory = articleCategory;
	}

	public String getArticleCategoryId() {
		return articleCategoryId;
	}

	public void setArticleCategoryId(String articleCategoryId) {
		this.articleCategoryId = articleCategoryId;
	}
    
    

}
