package com.jibo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FormulaRank.
 * 
 *  * 医学公式模块 - 常用公式
 * 
 */
public class FormulaRank implements java.io.Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 2618597203760809397L;
	private Integer id;
    /** Not-null value. */
    private String name;
    private Integer count;

    public FormulaRank() {
    }

    public FormulaRank(Integer id) {
        this.id = id;
    }

    public FormulaRank(Integer id, String name, Integer count) {
        this.id = id;
        this.name = name;
        this.count = count;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}
