package com.jibo.entity;

import java.util.List;
import com.jibo.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import com.jibo.dao.CategoryFormulaMappingDao;
import com.jibo.dao.FormulaCategoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table category.
 * 
 *  * 医学公式模块 - 公式类别
 * 
 */
public class FormulaCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7060893319817111824L;
	private Integer id;
	/** Not-null value. */
	private String name;

	/** Used to resolve relations */
	private transient DaoSession daoSession;

	/** Used for active entity operations. */
	private transient FormulaCategoryDao myDao;

	private List<CategoryFormulaMapping> categoryFormulaMappingList;

	public FormulaCategory() {
	}

	public FormulaCategory(Integer id) {
		this.id = id;
	}

	public FormulaCategory(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	/** called by internal mechanisms, do not call yourself. */
	public void __setDaoSession(DaoSession daoSession) {
		this.daoSession = daoSession;
		myDao = daoSession != null ? daoSession.getFormulaCategoryDao() : null;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/** Not-null value. */
	public String getName() {
		return name;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * To-many relationship, resolved on first access (and after reset). Changes
	 * to to-many relations are not persisted, make changes to the target
	 * entity.
	 */
	public synchronized List<CategoryFormulaMapping> getCategoryFormulaMappingList() {
		if (categoryFormulaMappingList == null) {
			if (daoSession == null) {
				throw new DaoException("Entity is detached from DAO context");
			}
			CategoryFormulaMappingDao targetDao = daoSession
					.getCategoryFormulaMappingDao();
			categoryFormulaMappingList = targetDao
					._queryFormulaCategory_CategoryFormulaMappingList(id);
		}
		return categoryFormulaMappingList;
	}

	/**
	 * Resets a to-many relationship, making the next get call to query for a
	 * fresh result.
	 */
	public synchronized void resetCategoryFormulaMappingList() {
		categoryFormulaMappingList = null;
	}

	/**
	 * Convenient call for {@link AbstractDao#delete(Object)}. Entity must
	 * attached to an entity context.
	 */
	public void delete() {
		if (myDao == null) {
			throw new DaoException("Entity is detached from DAO context");
		}
		myDao.delete(this);
	}

	/**
	 * Convenient call for {@link AbstractDao#update(Object)}. Entity must
	 * attached to an entity context.
	 */
	public void update() {
		if (myDao == null) {
			throw new DaoException("Entity is detached from DAO context");
		}
		myDao.update(this);
	}

	/**
	 * Convenient call for {@link AbstractDao#refresh(Object)}. Entity must
	 * attached to an entity context.
	 */
	public void refresh() {
		if (myDao == null) {
			throw new DaoException("Entity is detached from DAO context");
		}
		myDao.refresh(this);
	}

	@Override
	public String toString() {
		return name;
	}

}
