package com.jibo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table hospital_name.
 * 
 * 医院信息表
 * 
 */
public class Hospital {

    private Long id;
    private String name;
    private String namePY;//医院文字拼音首字母
    private String tierName;//-----级别：三甲，二甲。。。
    private String tierEnName;
    private Integer tierLevel;//---级别对应的int值
    private String provinceName;
    private String cityName;
    private String countyName;
    private String streetName;

    public Hospital() {
    }

    public Hospital(Long id) {
        this.id = id;
    }
    
    @Override
	public boolean equals(Object o) {
		return o.toString().equals(name);
	}

	@Override
	public String toString() {
		return name;
	}

    public Hospital(Long id, String name, String namePY, String tierName,
			String tierEnName, Integer tierLevel, String provinceName,
			String cityName, String countyName, String streetName) {
		super();
		this.id = id;
		this.name = name;
		this.namePY = namePY;
		this.tierName = tierName;
		this.tierEnName = tierEnName;
		this.tierLevel = tierLevel;
		this.provinceName = provinceName;
		this.cityName = cityName;
		this.countyName = countyName;
		this.streetName = streetName;
	}

	public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTierName() {
        return tierName;
    }

    public void setTierName(String tierName) {
        this.tierName = tierName;
    }

    public Integer getTierLevel() {
        return tierLevel;
    }

    public void setTierLevel(Integer tierLevel) {
        this.tierLevel = tierLevel;
    }

    public String getProvinceName() {
        return provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getCountyName() {
        return countyName;
    }

    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }

    public String getStreetName() {
        return streetName;
    }

    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

	public String getNamePY() {
		return namePY;
	}

	public void setNamePY(String namePY) {
		this.namePY = namePY;
	}

	public String getTierEnName() {
		return tierEnName;
	}

	public void setTierEnName(String tierEnName) {
		this.tierEnName = tierEnName;
	}
    

}
