package com.jibo.entity;

import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;

import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import com.jibo.common.Constant;
import com.jibo.common.Util;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table manufucture_brand_info.
 * 
 * 联系厂商所对应的厂商说明书详细信息表
 * 
 */
public class ManufutureBrandInfo {

	private String brandId;
	private String productId;
	private String generalName;
	private String zyName;
	private String enName;
	private String pyName;
	private String indication;
	private String contraindication;
	private String brandName;
	private String brandNameEn;
	private String mncId;
	private String otherInfo;
	private String manufacturerNameCn;
	private String manufacturerNameEn;

	public ManufutureBrandInfo() {
	}

	public ManufutureBrandInfo(String brandId) {
		this.brandId = brandId;
	}

	public ManufutureBrandInfo(String brandId, String productId,
			String generalName, String zyName, String enName, String pyName,
			String indication, String contraindication, String brandName,
			String brandNameEn, String mncId, String otherInfo,
			String manufacturerNameCn, String manufacturerNameEn) {
		this.brandId = brandId;
		this.productId = productId;
		this.generalName = generalName;
		this.zyName = zyName;
		this.enName = enName;
		this.pyName = pyName;
		this.indication = indication;
		this.contraindication = contraindication;
		this.brandName = brandName;
		this.brandNameEn = brandNameEn;
		this.mncId = mncId;
		this.otherInfo = otherInfo;
		this.manufacturerNameCn = manufacturerNameCn;
		this.manufacturerNameEn = manufacturerNameEn;
	}

	private String pediatric_use;
	private String geriatric_use;
	private String pregnancydesc;
	private String formulationCn;
	private String dosing;
	private String overDosage;
	private  String ADR;
	private  String drugInteraction;

	private ArrayList<String> specList;

	private class OtherInfo {
		private String pediatricuse;
		private String geriatricuse;
		private String pregnantwomen;
		private String formulation_cn;
		private String manufacturer_name_cn;
		private String manufacturer_name_en;
		private String dosing;
		private String adr;
		private String drug_interaction;
		private String overdosage;
		private String spec1;
		private String spec2;
		private String spec3;
		private String spec4;
		private String spec5;
	}

	public void paserJson() {
		if (otherInfo != null) {
			// JsonReader reader = new JsonReader(new StringReader(otherInfo));
			// try {
			// reader.beginObject();// 开始解析对象
			// specList = new ArrayList<String>();
			// String tagName;
			// String value;
			//
			// while (reader.hasNext()) {
			// tagName = reader.nextName();
			// value = reader.nextString();
			// value = value==null?"":value;
			// if (tagName.equals("pediatricuse")) {
			// pediatric_use = value;
			// } else if (tagName.equals("geriatricuse")) {
			// geriatric_use = value;
			// } else if (tagName.equals("pregnantwomen")) {
			// pregnancydesc = value;
			// } else if (tagName.equals("formulation_cn")) {
			// formulationCn = value;
			// } else if (tagName.equals("manufacturer_name_cn")) {
			// manufacturerNameCn = value;
			// } else if (tagName.equals("manufacturer_name_en")) {
			// manufacturerNameEn = value;
			// } else if (tagName.equals("dosing")) {
			// dosing = value;
			// } else if (tagName.equals("adr")) {
			// ADR = value;
			// } else if (tagName.equals("drug_interaction")) {
			// drugInteraction = value;
			// }else if (tagName.equals("overdosage")) {
			// overDosage = value;
			// }else if (tagName.equals("spec1")) {
			// specList.add(value);
			// } else if (tagName.equals("spec2")) {
			// specList.add(value);
			// } else if (tagName.equals("spec3")) {
			// specList.add(value);
			// } else if (tagName.equals("spec4")) {
			// specList.add(value);
			// } else if (tagName.equals("spec5")) {
			// specList.add(value);
			// } else {
			// reader.skipValue();
			// }
			// }
			// reader.endObject();// 结束对象解析
			// } catch (IOException e) {
			// e.printStackTrace();
			// }
			
			
			JsonReader reader = new JsonReader(new StringReader(otherInfo));
			OtherInfo info = new Gson().fromJson(reader, OtherInfo.class);
			if (info != null) {
				pediatric_use = null==info.pediatricuse?Constant.SPACE:info.pediatricuse;
				geriatric_use = null==info.geriatricuse?Constant.SPACE:info.geriatricuse; 
				pregnancydesc = null==info.pregnantwomen?Constant.SPACE:info.pregnantwomen; 
				formulationCn = null==info.formulation_cn?Constant.SPACE:info.formulation_cn; 
				manufacturerNameCn = null==info.manufacturer_name_cn?Constant.SPACE:info.manufacturer_name_cn;
				manufacturerNameEn =  null==info.manufacturer_name_en?Constant.SPACE:info.manufacturer_name_en;
				dosing = null==info.dosing?Constant.SPACE:info.dosing;
				ADR =  null==info.adr?Constant.SPACE:info.adr;
				drugInteraction = null==info.drug_interaction?Constant.SPACE:info.drug_interaction;
				overDosage = null==info.overdosage?Constant.SPACE:info.overdosage;
				specList = new ArrayList<String>();
				String s = info.spec1;
				if (null != s)
					specList.add(s);
				s = info.spec2;
				if (null != s)
					specList.add(s);
				s = info.spec3;
				if (null != s)
					specList.add(s);
				s = info.spec4;
				if (null != s)
					specList.add(s);
				s = info.spec5;
				if (null != s)
					specList.add(s);
			}
			// try {
			// JSONObject obj = new JSONObject(otherInfo);
			// pediatric_use = obj.optString("pediatricuse", Constant.SPACE);
			// geriatric_use = obj.optString("geriatricuse", Constant.SPACE);
			// pregnancydesc = obj.optString("pregnantwomen", Constant.SPACE);
			// formulationCn = obj.optString("formulation_cn", Constant.SPACE);
			// manufacturerNameCn = obj.optString("manufacturer_name_cn",
			// Constant.SPACE);
			// manufacturerNameEn = obj.optString("manufacturer_name_en",
			// Constant.SPACE);
			// dosing = obj.optString("dosing", Constant.SPACE);
			// ADR = obj.optString("adr", Constant.SPACE);
			// drugInteraction = obj.optString("drug_interaction",
			// Constant.SPACE);
			// overDosage = obj.optString("overdosage", Constant.SPACE);
			// specList = new ArrayList<String>();
			// String s = obj.optString("spec1", null);
			// if (!s.equals("null"))
			// specList.add(s);
			// s = obj.optString("spec2", null);
			// if (!s.equals("null"))
			// specList.add(s);
			// s = obj.optString("spec3", null);
			// if (!s.equals("null"))
			// specList.add(s);
			// s = obj.optString("spec4", null);
			// if (!s.equals("null"))
			// specList.add(s);
			// s = obj.optString("spec5", null);
			// if (!s.equals("null"))
			// specList.add(s);
			// } catch (JSONException e) {
			// e.printStackTrace();
			// }
		}
	}
	

	public String getPediatric_use() {
		return pediatric_use;
	}

	public void setPediatric_use(String pediatric_use) {
		this.pediatric_use = pediatric_use;
	}

	public String getGeriatric_use() {
		return geriatric_use;
	}

	public void setGeriatric_use(String geriatric_use) {
		this.geriatric_use = geriatric_use;
	}

	public String getPregnancydesc() {
		return pregnancydesc;
	}

	public void setPregnancydesc(String pregnancydesc) {
		this.pregnancydesc = pregnancydesc;
	}

	public String getFormulationCn() {
		return formulationCn;
	}

	public void setFormulationCn(String formulationCn) {
		this.formulationCn = formulationCn;
	}

	public String getDosing() {
		return dosing;
	}

	public void setDosing(String dosing) {
		this.dosing = dosing;
	}

	public String getOverDosage() {
		return overDosage;
	}

	public void setOverDosage(String overDosage) {
		this.overDosage = overDosage;
	}

	public String getADR() {
		return ADR;
	}

	public void setADR(String aDR) {
		ADR = aDR;
	}

	public String getDrugInteraction() {
		return drugInteraction;
	}

	public void setDrugInteraction(String drugInteraction) {
		this.drugInteraction = drugInteraction;
	}

	public ArrayList<String> getSpecList() {
		return specList;
	}

	public void setSpecList(ArrayList<String> specList) {
		this.specList = specList;
	}

	public String getBrandId() {
		return brandId;
	}

	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getGeneralName() {
		return generalName;
	}

	public void setGeneralName(String generalName) {
		this.generalName = generalName;
	}

	public String getZyName() {
		return zyName;
	}

	public void setZyName(String zyName) {
		this.zyName = zyName;
	}

	public String getEnName() {
		return enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	public String getPyName() {
		return pyName;
	}

	public void setPyName(String pyName) {
		this.pyName = pyName;
	}

	public String getIndication() {
		return indication;
	}

	public void setIndication(String indication) {
		this.indication = indication;
	}

	public String getContraindication() {
		return contraindication;
	}

	public void setContraindication(String contraindication) {
		this.contraindication = contraindication;
	}

	public String getBrandName() {
		return brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getBrandNameEn() {
		return brandNameEn;
	}

	public void setBrandNameEn(String brandNameEn) {
		this.brandNameEn = brandNameEn;
	}

	public String getMncId() {
		return mncId;
	}

	public void setMncId(String mncId) {
		this.mncId = mncId;
	}

	public String getOtherInfo() {
		return otherInfo;
	}

	public void setOtherInfo(String otherInfo) {
		this.otherInfo = otherInfo;
	}

	public String getManufacturerNameCn() {
		return manufacturerNameCn;
	}

	public void setManufacturerNameCn(String manufacturerNameCn) {
		this.manufacturerNameCn = manufacturerNameCn;
	}

	public String getManufacturerNameEn() {
		return manufacturerNameEn;
	}

	public void setManufacturerNameEn(String manufacturerNameEn) {
		this.manufacturerNameEn = manufacturerNameEn;
	}

}
