package com.jibo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TADrug.
 * 
 * 药品类别关系表
 * 
 */
public class TADrug {

	private String taId1;// 1级分类  (外键关联 TADrugRef的id)
	private String taId2;// 2级分类  (外键关联 TADrugRef的id)
	private String taId3;// 3级分类  (外键关联 TADrugRef的id)
	private String taId4;// 4级分类  (外键关联 TADrugRef的id)
	private String changeDate;
	private String drugId;//药品id

	public TADrug() {
	}

	public TADrug(String taId1, String taId2, String taId3, String taId4,
			String changeDate, String drugId) {
		this.taId1 = taId1;
		this.taId2 = taId2;
		this.taId3 = taId3;
		this.taId4 = taId4;
		this.changeDate = changeDate;
		this.drugId = drugId;
	}

	public String getTaId1() {
		return taId1;
	}

	public void setTaId1(String taId1) {
		this.taId1 = taId1;
	}

	public String getTaId2() {
		return taId2;
	}

	public void setTaId2(String taId2) {
		this.taId2 = taId2;
	}

	public String getTaId3() {
		return taId3;
	}

	public void setTaId3(String taId3) {
		this.taId3 = taId3;
	}

	public String getTaId4() {
		return taId4;
	}

	public void setTaId4(String taId4) {
		this.taId4 = taId4;
	}

	public String getChangeDate() {
		return changeDate;
	}

	public void setChangeDate(String changeDate) {
		this.changeDate = changeDate;
	}

	public String getDrugId() {
		return drugId;
	}

	public void setDrugId(String drugId) {
		this.drugId = drugId;
	}

}
