package com.jibo.entity;

import com.jibo.common.Util;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TADrugRef.
 * 
 * 药品类别信息表
 * 
 */
public class TADrugRef implements java.io.Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
    private String level;//级别，共四级分类：1,2,3,4
    private String nameEn;
    private String nameCn;
    private String changeDate;

    public TADrugRef() {
    }

    public TADrugRef(String id) {
        this.id = id;
    }

    public TADrugRef(String id, String level, String nameEn, String nameCn, String changeDate) {
        this.id = id;
        this.level = level;
        this.nameEn = nameEn;
        this.nameCn = nameCn;
        this.changeDate = changeDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getNameEn() {
        return nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getNameCn() {
        return nameCn;
    }

    public void setNameCn(String nameCn) {
        this.nameCn = nameCn;
    }

    public String getChangeDate() {
        return changeDate;
    }

    public void setChangeDate(String changeDate) {
        this.changeDate = changeDate;
    }

	@Override
	public String toString() {
		return Util.isZh()?nameCn:nameEn;
	}
    
    

}
