package com.jibo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table unit_values.
 * 
 * * 医学公式模块 - 公式详细内容的运算规则
 * 
 * 
 */
public class UnitValues implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -1864765016531640922L;
	private Integer id;
    private Integer unitId;
    private Integer type;
    private String valueCn;
    private String valueEn;
    private String key;

    public UnitValues() {
    }

    public UnitValues(Integer id) {
        this.id = id;
    }

    public UnitValues(Integer id, Integer unitId, Integer type, String valueCn, String valueEn, String key) {
        this.id = id;
        this.unitId = unitId;
        this.type = type;
        this.valueCn = valueCn;
        this.valueEn = valueEn;
        this.key = key;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUnitId() {
        return unitId;
    }

    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getValueCn() {
        return valueCn;
    }

    public void setValueCn(String valueCn) {
        this.valueCn = valueCn;
    }

    public String getValueEn() {
        return valueEn;
    }

    public void setValueEn(String valueEn) {
        this.valueEn = valueEn;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

	@Override
	public String toString() {
		return valueCn;
	}
    
    

}
